# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20170209_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipient_photos/'),
        ),
    ]
