# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_parcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInParcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='parcel',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
