# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_auto_20170213_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='cost_of_delivery',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
