# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_auto_20170213_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
