# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_auto_20170216_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinparcel',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductInParcel',
        ),
    ]
