# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_auto_20170216_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInParcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Parcel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Product')),
            ],
        ),
    ]
